// Generated by CoffeeScript 1.6.3
angular.module('ngPeacemakers.schools', ['ui.state', 'ngResource']).config(function($stateProvider) {
  return $stateProvider.state('schools', {
    url: '/schools',
    views: {
      "main": {
        controller: 'SchoolsCtrl',
        templateUrl: 'schools/schools.tpl.html'
      }
    },
    data: {
      pageTitle: 'Schools'
    }
  });
}).controller('SchoolsCtrl', function($scope, SchoolsRes) {
  return $scope.schools = SchoolsRes.query();
}).factory('SchoolsRes', function($resource) {
  return $resource('http://localhost:3000/api/schools');
});
